name: Build and Push to ECR
 
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
 
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
 
      - name: Build and push Docker image
        env:
          ECR_REGISTRY: 491085395209.dkr.ecr.ap-south-1.amazonaws.com
          ECR_REPOSITORY: sample-python-web-app
          IMAGE_TAG: python_Sample
        run: |
          RUN apt-get update && \
          apt-get install -y --no-install-recommends \
          build-essential \
          python3 \
          python3-pip \
          python3-dev && \
          apt-get clean && \
          rm -rf /var/lib/apt/lists/*
          RUN pip3 install --break-system-packages pipenv
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
